spring:
  application:
    name: organization-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8080
management:
  endpoints:
    web:
      exposure:
        include: env,health,refresh,info

