spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: https://github.com/mehdirahimi/whole.git
          search-paths: /configs
server:
  port: 8081
encrypt:
  key: 123@abc!p[]#cvb%yui&iop^e