spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8081
management:
  endpoints:
    web:
      exposure:
        include: env,health,refresh